WebProject/WebProject/Areas/Admin/Controllers/productsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebProject.Data;
using WebProject.Models;

namespace WebProject.Areas.Admin.Controllers
{
      [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class productsController : Controller
    {
        private readonly AppDbContext _context;

        public productsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: products
        public async Task<IActionResult> Index()
        {
            return _context.products != null ?
                        View(await _context.products.ToListAsync()) :
                        Problem("Entity set 'AppDbContext.products'  is null.");
        }

        // GET: products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.products == null)
            {
                return NotFound();
            }

            var product = await _context.products
                .FirstOrDefaultAsync(m => m.productid == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: products/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
          [HttpPost]
          [ValidateAntiForgeryToken]
          public async Task<IActionResult> Create([Bind("productid,name,description,quantity,price,image")] product product)
          {
              if (ModelState.IsValid)
              {
                  _context.Add(product);
                  await _context.SaveChangesAsync();
                  Debug.WriteLine("Product added to database: " + product);
                  return RedirectToAction(nameof(Index));
              }
              Debug.WriteLine("ModelState errors:");
              foreach (var modelStateEntry in ModelState.Values)
              {
                  foreach (var error in modelStateEntry.Errors)
                  {
                      Debug.WriteLine(error.ErrorMessage);
                  }
              }
              return View(product);
          }
      /*  [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IFormFile file, [Bind("productid,name,description,quantity,price")] product product)
        {
            if (ModelState.IsValid)
            {
                if (file != null && file.Length > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/", fileName);
                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await file.CopyToAsync(fileStream);
                    }
                    product.image = fileName;
                }

                _context.Add(product);
                await _context.SaveChangesAsync();
                Debug.WriteLine("Product added to database: " + product);
                return RedirectToAction(nameof(Index));
            }

            Debug.WriteLine("ModelState errors:");
            foreach (var modelStateEntry in ModelState.Values)
            {
                foreach (var error in modelStateEntry.Errors)
                {
                    Debug.WriteLine(error.ErrorMessage);
                }
            }

            return View(product);
        }

        */


        // GET: products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.products == null)
            {
                return NotFound();
            }

            var product = await _context.products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST: products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("productid,name,description,quantity,price,image")] product product)
        {
            if (id != product.productid)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!productExists(product.productid))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.products == null)
            {
                return NotFound();
            }

            var product = await _context.products
                .FirstOrDefaultAsync(m => m.productid == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.products == null)
            {
                return Problem("Entity set 'AppDbContext.products'  is null.");
            }
            var product = await _context.products.FindAsync(id);
            if (product != null)
            {
                _context.products.Remove(product);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool productExists(int id)
        {
            return (_context.products?.Any(e => e.productid == id)).GetValueOrDefault();
        }
    }
}

WebProject/WebProject/Areas/Customer/Controllers/ordersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Diagnostics;
using System.Security.Claims;
using WebProject.Models;
using WebProject.Repositories;

namespace WebProject.Areas.Customer.Controllers
{
    [Area("Customer")]
    [Authorize]
    public class ordersController : Controller
    {
        public IUnitOfWork _unitOfWork { get; set; }
        public ordersController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index(int pageNumber = 1, int pageSize = 5)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            string currentUserId = claim.Value;

            int skipCount = (pageNumber - 1) * pageSize;

            IEnumerable<order> orders = _unitOfWork.order.GetAll(o => o.userid == currentUserId)
                                                        .OrderByDescending(o => o.date_order)
                                                        .Skip((pageNumber - 1) * pageSize)
                                                        .Take(pageSize)
                                                        .ToList();
            int totalOrders = _unitOfWork.order.GetAll(o => o.userid == currentUserId).Count();

            ViewBag.PageNumber = pageNumber;
            ViewBag.PageSize = pageSize;
            ViewBag.TotalPages = (int)Math.Ceiling((double)totalOrders / pageSize);

            return View(orders);
        }
        [HttpGet]
        public IActionResult OrderDetails(int orderId)
        {
            // Fetch the order details including related order_product records
            var orderDetail = _unitOfWork.orderDetail.GetT(o => o.orderid == orderId);

            if (orderDetail == null)
            {
                return View("Error");
            }

            // Fetch the related order_product records
            var orderProducts = _unitOfWork.product_order.GetAll(op => op.orderid == orderId, includeProperties: "product");
            // Create a view model to hold both the order details and the ordered products
            var viewModel = new OrderDetailsViewModel
            {
                OrderDetail = orderDetail,
                OrderedProducts = orderProducts.ToList()
            };

            return View(viewModel);
        }
    }
}

WebProject/WebProject/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<user> SignInManager
@inject UserManager<user> UserManager

@{
    var isAdmin = false;

    if (SignInManager.IsSignedIn(User))
    {
        var user = await UserManager.GetUserAsync(User);
        isAdmin = await UserManager.IsInRoleAsync(user, "Admin");
    }
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ECommerce App</title>
    <link rel="stylesheet" href="~/css/Sketchy.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebProject.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.0/css/all.min.css" crossorigin="anonymous">
</head>
<body>
    <header>
        @*
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="products" >Products</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>*@
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand"  asp-area="customer" asp-action="Index" asp-controller="home">ECommerce App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a  asp-area="customer" asp-action="Index" asp-controller="home" class="nav-link active" >
                                Home
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>
                        @if (isAdmin)
                        {
                            <li class="nav-item">
                               <a class="nav-link" asp-controller="Home" asp-action="AdminDashboard">Dashboard</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Admin" asp-action="Index" asp-controller="products">Product Management</a>
                            </li>

                        }
                        @* <li class="nav-item">
                        <a class="nav-link" href="#">About</a>
                        </li>
                        <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                        <div class="dropdown-menu">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Separated link</a>
                        </div>
                        </li>*@
                    </ul>
					
                    <div class="d-flex justify-content-between">
                        <div class="d-inline-block me-2">
                         <a class="btn btn-outline-success" asp-area="Customer" asp-action="Index" asp-controller="OrderProduct"><i class="bi bi-cart"></i>Cart</a>
                       </div>

                    @*   <div class="d-inline-block me-2">
                         <a class="btn btn-outline-light" asp-area="Customer" asp-action="Index" asp-controller="orders">Order</a>
                       </div>*@
                         
                        <partial name="_LoginPartial" />
                        @*   <div class="d-flex">
                            <button class="btn btn-warning my-2 me-2 my-sm-0" type="submit">Login</button>
                            <button class="btn btn-danger my-2 my-sm-0" type="submit">Registre</button>
                        </div>>*@
                    </div
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ECommerce App - By YassineAsmi
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>