WebProject/WebProject/Models/order_product.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebProject.Models
{
    public class order_product
    {
        public int orderid { get; set; }
        public order order { get; set; }

        public int productid { get; set; }
        public product product { get; set; }
        public int quantity { get; set; }
        // Add the new property
        public bool isInCart { get; set; }
        //Relationship user
        public string userid { get; set; }
        [ValidateNever]
        [ForeignKey("userid")]
        public user users { get; set; }
    }

}

WebProject/WebProject/Areas/Customer/Controllers/orderProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Security.Claims;
using WebProject.Models;
using WebProject.Repositories;
using Microsoft.Extensions.Hosting;


using System.Drawing;
using PdfSharp;
using PdfSharp.Drawing;
using PdfSharp.Pdf;
using PdfSharp.Pdf.IO;
using MigraDoc.DocumentObjectModel;
using MigraDoc.Rendering;
using Microsoft.Extensions.Hosting;
using Microsoft.EntityFrameworkCore;

namespace WebProject.Areas.Customer.Controllers
{
    [Area("Customer")]
    [Authorize]
    public class orderProductController : Controller
    {
        private IUnitOfWork _unitOfWork;
        public CartVM vm { get; set; }
        private readonly IWebHostEnvironment _webHostEnvironment;

        public orderProductController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;

        }

        public IActionResult Index()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            vm = new CartVM()
            {
                Order = new Models.order(),
                ListCart = _unitOfWork.product_order.GetAll(u => u.userid == claim.Value && u.isInCart == true, includeProperties: "product,order")
            };

            double total = 0;
            int qty = 0;
            foreach (var list in vm.ListCart)
            {
                total += (list.product.price * list.quantity);
            }

            vm.Order.total = total;

            return View(vm);
        }

        public IActionResult AddToCart(int productId, int quantity)
        {
            // Get the current user
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            // Check if there's an existing order for the user
            var existingOrder = _unitOfWork.order.GetT(o => o.userid == claim.Value && o.status == "Pending");

            // If there's no existing order, create a new order
            if (existingOrder == null)
            {
                existingOrder = new order
                {
                    // Set the order properties (e.g., userid, order_date, etc.)
                    userid = claim.Value,
                    date_order = DateTime.Now,
                    status = "Pending",
                    total = 0,
                };
                _unitOfWork.order.Add(existingOrder);
                _unitOfWork.Save();
            }

            // Get the product and its current stock
            var product = _unitOfWork.product.GetT(p => p.productid == productId);
            var currentStock = product.quantity;
            Debug.Print("product quantity: " + quantity);

            // Check if the requested quantity exceeds the available stock
            if (quantity > currentStock)
            {
                // Handle the out-of-stock scenario
                TempData["ErrorMessage"] = "Sorry, the requested quantity exceeds the available stock.";
                return RedirectToAction("Index", "Home");
            }
            // Check if the product is already in the cart
            var existingOrderProduct = _unitOfWork.product_order.GetT(x => x.orderid == existingOrder.orderid && x.productid == productId);

            if (existingOrderProduct == null)
            {

                // If the product is not in the cart, create a new order product
                var orderProduct = new order_product
                {
                    userid = claim.Value,
                    productid = productId,
                    product = product,
                    quantity = Math.Min(quantity, currentStock), // Limit the quantity to the current stock
                    order = existingOrder,
                    isInCart = true
                };
                _unitOfWork.product_order.Add(orderProduct);

                // Add the order detail
                var user = _unitOfWork.user.GetT(x => x.Id == claim.Value);
                var orderDetail = new orderDetail
                {
                    orderid = existingOrder.orderid,
                    productid = productId,
                    Name = user.first_name + " " + user.last_name,
                    PhoneNumber = user.phone_number,
                    Address = user.Address,
                    price = product.price,
                    quantity = quantity,
                    userid = claim.Value
                };
                _unitOfWork.orderDetail.Add(orderDetail);
            }
            else
            {
                // If the product is already in the cart, update the quantity
                existingOrderProduct.quantity = Math.Min(existingOrderProduct.quantity + quantity, currentStock); // Limit the quantity to the current stock
            }

            // Update the order total
            existingOrder.total += product.price * quantity;

            // Save the changes to the database
            _unitOfWork.order.update(existingOrder);
            _unitOfWork.Save();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Plus(int orderid, int productid)
        {
            var orderProduct = _unitOfWork.product_order.GetT(u => u.orderid == orderid && u.productid == productid);
            if (orderProduct != null)
            {
                
                var product = _unitOfWork.product.GetT(u => u.productid == productid);

                if (product != null && product.quantity > orderProduct.quantity)
                {
                    orderProduct.quantity++;
                    _unitOfWork.Save();
                }
            }
            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult Minus(int orderid, int productid)
        {
            var orderProduct = _unitOfWork.product_order.GetT(u => u.orderid == orderid && u.productid == productid);
            if (orderProduct != null)
            {
                if (orderProduct.quantity > 1)
                {
                    orderProduct.quantity--;
                }
                else
                {
                    _unitOfWork.product_order.delete(orderProduct);
                }
                _unitOfWork.Save();
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Delete(int orderid, int productid)
        {
            var orderProduct = _unitOfWork.product_order.GetT(u => u.orderid == orderid && u.productid == productid);
            if (orderProduct != null)
            {
                _unitOfWork.product_order.delete(orderProduct);
                _unitOfWork.Save();
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Summary()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claims = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            // Add this line to get the orderId
            int orderIdd = _unitOfWork.order.GetT(o => o.userid == claims.Value && o.status == "Pending").orderid;

            vm = new CartVM()
            {
                ListCart = _unitOfWork.product_order.GetAll(u => u.userid == claims.Value && u.isInCart == true, includeProperties: "product,order"),
                OrderDetail = new orderDetail(),
                OrderedProducts = _unitOfWork.product_order.GetAll(u => u.userid == claims.Value && u.orderid == orderIdd, includeProperties: "product")
            };
            vm.OrderDetail.users = _unitOfWork.user.GetT(u => u.Id == claims.Value);
            vm.OrderDetail.Name = vm.OrderDetail.users.first_name + " " + vm.OrderDetail.users.last_name;
            vm.OrderDetail.PhoneNumber = vm.OrderDetail.users.phone_number;
            vm.OrderDetail.Address = vm.OrderDetail.users.Address;

            double total = 0;
            foreach (var list in vm.ListCart)
            {
                total += (list.product.price * list.quantity);
            }
            Debug.WriteLine("Total: "+total.ToString());
            vm.OrderDetail.total = total;

            return View(vm);
        }


        public IActionResult OrderSuccess()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claims = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            int orderId = _unitOfWork.order.GetT(o => o.userid == claims.Value && o.status == "Pending")?.orderid ?? 0;
            var orderDet = _unitOfWork.orderDetail.GetT(o => o.orderid == orderId);

            var orderList = _unitOfWork.product_order.GetAll(u => u.userid == claims.Value && u.orderid == orderId, includeProperties: "product,users");

            // Create an instance of OrderDetailsViewModel
            var orderDetailsViewModel = new OrderDetailsViewModel
            {
                OrderDetail = orderDet,
                // Assign the list of ordered products
                OrderedProducts = orderList.ToList()
            };

            // Decrement the stock quantity for each product in the order
            foreach (var orderProduct in orderList)
            {
                // Retrieve the product from the database
                var product = _unitOfWork.product.GetT(p => p.productid == orderProduct.productid);

                // Update the stock quantity
                product.quantity -= orderProduct.quantity;

                // Save the updated product to the database
                _unitOfWork.product.Update(product);
            }

            // Calculate the total price based on the updated product_order records
            double totalPrice = orderList.Sum(item => item.product.price * item.quantity);

WebProject/WebProject/Areas/Customer/Views/orderProduct/Index.cshtml
@model WebProject.Models.CartVM
@{
    ViewData["Title"] = "Cart";
}

<section class="h-100" style="background-color: #000;">
    <div class="container h-100 py-5">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-10">
                <div class="d-flex justify-content-between align-items-center mb-6">
                    <h3 class="fw-normal mb-4 text-light">Shopping Cart</h3>
                </div>

                @foreach (var item in Model.ListCart)
                {
                    
                    <div class="card rounded-3 mb-4">
                        <div class="card-body p-4">
                            <div class="row d-flex justify-content-between align-items-center">
                                <div class="col-md-2 col-lg-2 col-xl-2">
                                    <img src="@item.product.image" class="img-fluid rounded-3" alt="Cotton T-shirt">
                                </div>
                                <div class="col-md-3 col-lg-3 col-lg-2">
                                    <p class="lead fw-normal mb-2">@item.product.name</p>
                                    <p class="text-muted">@Html.Raw(item.product.description)</p>
                                </div>
                                <div class="col-md-8 col-lg-6 col-xl-4 offset-lg-3">
                                    <div class="d-flex align-items-center">
                                        <h5 class="mb-0"> Price @item.product.price</h5>
                                        <h5 class="mb-0 mx-2">x @item.quantity</h5>

                                        <a class="btn btn-outline-success mx-1" asp-action="plus" asp-route-orderid="@item.orderid" asp-route-productid="@item.productid">
                                            <i class="bi bi-plus-lg"></i>
                                        </a>
                                        <a class="btn btn-outline-primary mx-1" asp-action="minus" asp-route-orderid="@item.orderid" asp-route-productid="@item.productid" class="btn btn-link px-2">
                                            <i class="bi bi-dash-lg"></i>
                                        </a>
                                        <a class="btn btn-outline-danger mx-1" asp-action="delete" asp-route-orderid="@item.orderid" asp-route-productid="@item.productid" class="btn btn-link px-2">
                                            <i class="bi bi-trash-fill"></i>
                                        </a>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                }

                <div class="row">
                    <div class="col-md-6">
                        <h3>Total: @Model.Order.total</h3>
                    </div>
                    <div class="col-md-6 text-right">
                        <a asp-controller="orderProduct" asp-action="Summary" class="btn btn-primary">Checkout</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

WebProject/WebProject/Areas/Customer/Views/orderProduct/OrderSuccess.cshtml
@model WebProject.Models.OrderDetailsViewModel
@{
    ViewData["Title"] = "Order Success";
}

<div class="container mt-5">
    <div class="row">
        <div class="col-md-12 text-center">
            <img src="~/images/ORDERSUCC.png" alt="Order success" />
            <h1 class="display-4">Order Successfully Placed!</h1>
            <p class="lead">Thank you for your purchase. Your order has been placed successfully.</p>
            <a class="btn btn-primary" asp-area="customer" asp-action="Index" asp-controller="Home">Back to Home</a>
            <a asp-area="customer" asp-action="DownloadInvoice" asp-controller="orderProduct" asp-route-orderId="@Model.OrderDetail.orderid" class="btn btn-secondary">Download Invoice</a>
        </div>
    </div>
</div>

WebProject/WebProject/Areas/Customer/Views/orderProduct/Summary.cshtml
<h1>Summary</h1>
@model WebProject.Models.CartVM
@{
    ViewData["Title"] = "Summary";
}



    <div class="col-md-16 mb-6">
        <div class="card border-primary mb-4">
            <div class="card-header py-2">
                <h5 class="mb-0">Shipping details</h5>
            </div>
            <div class="card-body">
                <!-- Shipping details content -->
                <form method="post">
                    <div class="row">
                        <div class="col-md-12 mb-6">
                            <div class="card text-white bg-dark mb-3 ">

                                <div class="card-body">
                                    <div class="row mb-4">
                                        <div class="col">
                                            <div class="form-outline">
                                                <div class="d-flex align-items-center ">
                                                    <label class="form-label "><b>Name: </b></label>
                                                    <input type="text" value="@Model.OrderDetail.Name" class="form-control ms-3" disabled />
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row mb-4">
                                        <div class="col">
                                            <div class="form-outline">
                                                <div class="d-flex align-items-center ">
                                                    <label class="form-label "><b>Phone: </b></label>
                                                    <input type="text" value="@Model.OrderDetail.PhoneNumber" class="form-control ms-3" disabled />
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row mb-4">
                                        <div class="col">
                                            <div class="form-outline">
                                                <div class="d-flex align-items-center me-1">
                                                    <label class="form-label me-2"><b>Address: </b></label>
                                                    <textarea rows="3" class="form-control" disabled>@Model.OrderDetail.Address</textarea>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
     </div>
<form method="post" asp-controller="orderProduct" asp-action="OrderSuccess">
    <div class="col-md-16">
        <div class="card border-primary mb-3">
            <div class="card-header py-3">
                <h5 class="mb-0">Order Summary</h5>
            </div>
            <div class="card-body">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th></th>
                            <th scope="col">Product Name</th>
                            <th scope="col">Price</th>
                            <th scope="col">Quantity</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.ListCart)
                        {
                            <tr>
                                <td><b><img src="@item.product.image" width="100px" height="100px"></img> </b></td>
                                <td class="table-active"><b class="badge bg-info">@item.product.name</b></td>
                                <td class="table-active"><span class="badge bg-danger">@(item.product.price * item.quantity) Dt</span></td>
                                <td class="table-active"> <span class="badge bg-warning rounded-pill">@item.quantity</span></td>
                            </tr>
                        }
                    </tbody>
                </table>
                <div class="d-flex justify-content-between align-items-center mt-3">
                    <h4>Total:</h4>
                    <h4 class="text-light">@Model.OrderDetail.total Dt</h4>
                </div>
                <div class="d-grid mt-3">
                    <button type="submit" class="btn btn-success">Proceed to Pay</button>
                </div>
            </div>
        </div>

       
    </div>
</form>